// Generated by ChatGPT

#include <iostream>
#include <fstream>
#include <string>
#include <experimental\filesystem>

int main()
{
    using namespace std::experimental::filesystem;
    path source(current_path());
    source /= "Source.bin";

    path dest(current_path());
    dest /= "Copy.bin";

    if (exists(dest))
    {
        std::cout << "File already exists. Do you want to overwrite? (y/n): ";
        char choice;
        std::cin >> choice;
        if (choice != 'y')
        {
            return 0;
        }
    }

    std::ifstream input{source, std::ios::binary};
    if (!input)
    {
        std::cout << "Source file not found" << std::endl;
        return -1;
    }
    std::ofstream output{dest, std::ios::binary};
    if (!output)
    {
        std::cout << "Could not create output file" << std::endl;
        return -1;
    }

    // Determine the size of the input file
    input.seekg(0, std::ios::end);
    std::streampos size = input.tellg();
    input.seekg(0, std::ios::beg);

    // Read and write the contents of the input file
    char* buffer = new char[size];
    input.read(buffer, size);
    if (!input)
    {
        std::cout << "Error reading input file" << std::endl;
        return -1;
    }
    output.write(buffer, size);
    if (!output)
    {
        std::cout << "Error writing output file" << std::endl;
        return -1;
    }

    input.close();
    output.close();
    delete[] buffer;

    std::cout << "File copied successfully" << std::endl;
    return 0;
}
